version: '3.5'
services:
  dst-server:
    container_name: dst
    image: jamesits/dst-server:latest
    restart: "on-failure:5"
    ports:
      - "10999-11000:10999-11000/udp"
      - "12346-12347:12346-12347/udp"
    volumes:
      - ./data:/data
      # Uncomment to run surface world only
      # - ./supervisor.conf:/etc/supervisor/supervisor.conf:ro
    stop_grace_period: 6m
